name: webhook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35.4.0
        with:
          json: "true"

      - name: list all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file"
          done
      - name: request to insert content to DB
        # if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: ${{ secrets.API_KEY }}" -d "${{ steps.changed-files.outputs.all_changed_files }}" https://us-central1-my-blog-f6525.cloudfunctions.net/createArticle
